## YAML Template.
---
CircuitTicks: 1
ASCII_3:
  - 
    name: "0"
    lines:
      - XXX
      - X_X
      - XXX
  -
    name: "1"
    lines:
      - _X_
      - _X_
      - _X_
  -
    name: "2"
    lines:
      - X_X
      - X_X
      - X_X
  -
    name: "3"
    lines:
      - XXX
      - __X
      - XXX
  -
    name: "4"
    lines:
      - X_X
      - XXX
      - __X
  -
    name: "5"
    lines:
      - X_X
      - X_X
      - _X_
  -
    name: "6"
    lines:
      - _XX
      - X__
      - _XX
  -
    name: "7"
    lines:
      - XXX
      - __X
      - __X
  -
    name: "8"
    lines:
      - _X_
      - X_X
      - _X_
  -
    name: "9"
    lines:
      - _XX
      - X_X
      - _XX
  -
    name: "A"
    lines:
      - X_X
      - _X_
      - X_X
  -
    name: "B"
    lines:
      - _X_
      - XXX
      - _X_
  -
    name: "C"
    lines:
      - X__
      - _X_
      - _X_
  -
    name: "D"
    lines:
      - __X
      - _X_
      - _X_
  -
    name: "E"
    lines:
      - ___
      - ___
      - ___
  -
    name: "F"
    lines:
      - XXX
      - XXX
      - XXX
ASCII_5:
  - 
    name: "0"
    lines:
      - _XXX_
      - X___X
      - X___X
      - X___X
      - _XXX_
  -
    name: "1"
    lines:
      - ___X_
      - __XX_
      - _X_X_
      - ___X_
      - ___X_
  -
    name: "2"
    lines:
      - _XXX_
      - X___X
      - __XX_
      - _X___
      - XXXXX
  -
    name: "3"
    lines:
      - _XXX_
      - X___X
      - __XX_
      - X___X
      - _XXX_
  -
    name: "4"
    lines:
      - ___X_
      - __XX_
      - _X_X_
      - XXXXX
      - ___X_
  -
    name: "5"
    lines:
      - XXXXX
      - X____
      - XXXX_
      - ____X
      - XXXX_
  -
    name: "6"
    lines:
      - _XXX_
      - X____
      - XXXX_
      - X___X
      - _XXX_
  -
    name: "7"
    lines:
      - XXXXX
      - ____X
      - ___X_
      - __X__
      - __X__
  -
    name: "8"
    lines:
      - _XXX_
      - X___X
      - _XXX_
      - X___X
      - _XXX_
  -
    name: "9"
    lines:
      - _XXX_
      - X___X
      - _XXXX
      - ____X
      - _XXX_
  -
    name: "A"
    lines:
      - _XXX_
      - X___X
      - XXXXX
      - X___X
      - X___X
  -
    name: "B"
    lines:
      - XXXX_
      - X___X
      - XXXXX
      - X___X
      - XXXX_
  -
    name: "B"
    lines:
      - _XXX_
      - X___X
      - X____
      - X___X
      - _XXX_
  -
    name: "D"
    lines:
      - XXXX_
      - X___X
      - X___X
      - X___X
      - XXXX_
  -
    name: "E"
    lines:
      - XXXXX
      - X____
      - XXXX_
      - X____
      - XXXXX
  -
    name: "F"
    lines:
      - XXXXX
      - X____
      - XXXX_
      - X____
      - X____
ASCII_7:
  - 
    name: "0"
    lines:
      - __XXX__
      - _X___X_
      - _X___X_
      - _X___X_
      - _X___X_
      - _X___X_
      - __XXX__
  -
    name: "1"
    lines:
      - ____X__
      - ___XX__
      - __X_X__
      - _X__X__
      - ____X__
      - ____X__
      - ____X__
  -
    name: "2"
    lines:
      - __XXX__
      - _X___X_
      - _____X_
      - ___XX__
      - __X____
      - _X_____
      - _XXXXX_
  -
    name: "3"
    lines:
      - __XXX__
      - _X___X_
      - _____X_
      - ___XX__
      - _____X_
      - _X___X_
      - __XXX__
  -
    name: "4"
    lines:
      - _____X_
      - ____XX_
      - ___X_X_
      - __X__X_
      - _XXXXXX
      - _____X_
      - _____X_
  -
    name: "5"
    lines:
      - _XXXXX_
      - _X_____
      - _X_____
      - __XXX__
      - _____X_
      - _X___X_
      - __XXX__
  -
    name: "6"
    lines:
      - __XXX__
      - _X_____
      - _X_____
      - _XXXX__
      - _X___X_
      - _X___X_
      - __XXX__
  -
    name: "7"
    lines:
      - _XXXXX_
      - _____X_
      - ____X__
      - ___X___
      - ___X___
      - ___X___
      - ___X___
  -
    name: "8"
    lines:
      - __XXX__
      - _X___X_
      - _X___X_
      - __XXX__
      - _X___X_
      - _X___X_
      - __XXX__
  -
    name: "9"
    lines:
      - __XXX__
      - _X___X_
      - _X___X_
      - __XXXX_
      - _____X_
      - _____X_
      - __XXX__
  -
    name: "A"
    lines:
      - __XXXX_
      - _X____X
      - _X____X
      - _XXXXXX
      - _X____X
      - _X____X
      - _X____X
  -
    name: "B"
    lines:
      - _XXXXX_
      - _X____X
      - _X____X
      - _XXXXX_
      - _X____X
      - _X____X
      - _XXXXX_
  -
    name: "C"
    lines:
      - __XXXX_
      - _X____X
      - _X_____
      - _X_____
      - _X_____
      - _X____X
      - __XXXX_
  -
    name: "D"
    lines:
      - _XXXXX_
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - _XXXXX_
  -
    name: "E"
    lines:
      - _XXXXXX
      - _X_____
      - _X_____
      - _XXXX__
      - _X_____
      - _X_____
      - _XXXXXX
  -
    name: "F"
    lines:
      - _XXXXXX
      - _X_____
      - _X_____
      - _XXXX__
      - _X_____
      - _X_____
      - _X_____
  -
    name: "G"
    lines:
      - __XXXX_
      - _X____X
      - _X_____
      - _X__XXX
      - _X____X
      - _X____X
      - __XXXX_
  -
    name: "H"
    lines:
      - _X____X
      - _X____X
      - _X____X
      - _XXXXXX
      - _X____X
      - _X____X
      - _X____X
  -
    name: "I"
    lines:
      - __XXX__
      - ___X___
      - ___X___
      - ___X___
      - ___X___
      - ___X___
      - __XXX__
  -
    name: "J"
    lines:
      - __XXXX_
      - ____X__
      - ____X__
      - ____X__
      - ____X__
      - ____X__
      - __XX___
  -
    name: "K"
    lines:
      - _X____X
      - _X___X_
      - _X__X__
      - _XXX___
      - _X__X__
      - _X___X_
      - _X____X
  -
    name: "L"
    lines:
      - _X_____
      - _X_____
      - _X_____
      - _X_____
      - _X_____
      - _X____X
      - _XXXXXX
  -
    name: "M"
    lines:
      - _X____X
      - _XX__XX
      - _X_XX_X
      - _X_XX_X
      - _X____X
      - _X____X
      - _X____X
  -
    name: "N"
    lines:
      - _X____X
      - _XX___X
      - _X_X__X
      - _X_XX_X
      - _X__X_X
      - _X___XX
      - _X____X
  -
    name: "O"
    lines:
      - __XXXX_
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - __XXXX_
  -
    name: "P"
    lines:
      - _XXXXX_
      - _X____X
      - _X____X
      - _XXXXX_
      - _X_____
      - _X_____
      - _X_____
  -
    name: "Q"
    lines:
      - __XXXX_
      - _X____X
      - _X____X
      - _X____X
      - _X__X_X
      - _X___X_
      - __XXX_X
  -
    name: "R"
    lines:
      - _XXXXX_
      - _X____X
      - _X____X
      - _XXXXX_
      - _X__X__
      - _X___X_
      - _X____X
  -
    name: "S"
    lines:
      - __XXXX_
      - _X____X
      - _X_____
      - __XXXX_
      - ______X
      - _X____X
      - __XXXX_
  -
    name: "T"
    lines:
      - _XXXXX_
      - ___X___
      - ___X___
      - ___X___
      - ___X___
      - ___X___
      - ___X___
  -
    name: "U"
    lines:
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - __XXXX_
  -
    name: "V"
    lines:
      - _X____X
      - _X____X
      - _X____X
      - __X__X_
      - __X__X_
      - ___XX__
      - ___XX__
  -
    name: "W"
    lines:
      - _X____X
      - _X____X
      - _X____X
      - _X____X
      - _X_XX_X
      - _XX__XX
      - _X____X
  -
    name: "X"
    lines:
      - _X____X
      - __X__X_
      - __X__X_
      - ___XX__
      - __X__X_
      - __X__X_
      - _X____X
  -
    name: "Y"
    lines:
      - _X____X
      - __X__X_
      - __X__X_
      - ___XX__
      - ____X__
      - ____X__
      - ____X__
  -
    name: "Z"
    lines:
      - _XXXXXX
      - ______X
      - _____X_
      - ___XX__
      - __X____
      - _X_____
      - _XXXXXX
  -
    name: " "
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - _______
      - _______
  -
    name: "Block"
    lines:
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
  -
    name: "_"
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - _______
      - XXXXXXX
  -
    name: "-"
    lines:
      - _______
      - _______
      - _______
      - _XXXXX_
      - _______
      - _______
      - _______
  -
    name: "+"
    lines:
      - _______
      - ___X___
      - ___X___
      - _XXXXX_
      - ___X___
      - ___X___
      - _______
  -
    name: "*"
    lines:
      - _______
      - _X_X_X_
      - __XXX__
      - _XXXXX_
      - __XXX__
      - _X_X_X_
      - _______
  -
    name: ":"
    lines:
      - _______
      - _______
      - ___X___
      - _______
      - ___X___
      - _______
      - _______
  -
    name: "/"
    lines:
      - ______X
      - _____X_
      - ____X__
      - ___X___
      - __X____
      - _X_____
      - X______
  -
    name: ","
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - ___X___
      - __X____
  -
    name: "."
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - __XX___
      - __XX___
  -
    name: ";"
    lines:
      - _______
      - _______
      - _______
      - ___X___
      - _______
      - ___X___
      - __X____
  -
    name: "<"
    lines:
      - _______
      - ___XX__
      - _XX____
      - XX_____
      - _XX____
      - ___XX__
      - _______
  -
    name: ">"
    lines:
      - _______
      - __XX___
      - ____XX_
      - _____XX
      - ____XX_
      - __XX___
      - _______
  -
    name: "("
    lines:
      - ___XX__
      - __XX___
      - _XX____
      - _X_____
      - _XX____
      - __XX___
      - ___XX__
  -
    name: ")"
    lines:
      - __XX___
      - ___XX__
      - ____XX_
      - _____X_
      - ____XX_
      - ___XX__
      - __XX___
  -
    name: "Line 1"
    lines:
      - XXXXXXX
      - _______
      - _______
      - _______
      - _______
      - _______
      - _______
  -
    name: "Line 2"
    lines:
      - _______
      - XXXXXXX
      - _______
      - _______
      - _______
      - _______
      - _______
  -
    name: "Line 3"
    lines:
      - _______
      - _______
      - XXXXXXX
      - _______
      - _______
      - _______
      - _______
  -
    name: "Line 4"
    lines:
      - _______
      - _______
      - _______
      - XXXXXXX
      - _______
      - _______
      - _______
  -
    name: "Line 5"
    lines:
      - _______
      - _______
      - _______
      - _______
      - XXXXXXX
      - _______
      - _______
  -
    name: "Line 6"
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - XXXXXXX
      - _______
  -
    name: "Line 7"
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - _______
      - XXXXXXX
  -
    name: "Block LT"
    lines:
      - XXXX___
      - XXXX___
      - XXXX___
      - XXXX___
      - _______
      - _______
      - _______
  -
    name: "Block LB"
    lines:
      - _______
      - _______
      - _______
      - XXXX___
      - XXXX___
      - XXXX___
      - XXXX___
  -
    name: "Block RT"
    lines:
      - ___XXXX
      - ___XXXX
      - ___XXXX
      - ___XXXX
      - _______
      - _______
      - _______
  -
    name: "Block RB"
    lines:
      - _______
      - _______
      - _______
      - ___XXXX
      - ___XXXX
      - ___XXXX
      - ___XXXX
  -
    name: "Fill 2"
    lines:
      - _______
      - _______
      - _______
      - _______
      - _______
      - XXXXXXX
      - XXXXXXX
  -
    name: "Fill 3"
    lines:
      - _______
      - _______
      - _______
      - _______
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
  -
    name: "Fill 4"
    lines:
      - _______
      - _______
      - _______
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
  -
    name: "Fill 5"
    lines:
      - _______
      - _______
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
  -
    name: "Fill 6"
    lines:
      - _______
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
      - XXXXXXX
  -
    name: "Smile"
    lines:
      - _______
      - _X___X_
      - _______
      - ___X___
      - X_____X
      - _X___X_
      - __XXX__
