## YAML Template.
---
name: Circuit
main: com.mahn42.anhalter42.circuit.Circuit
version: 0.23
depend: [MAHN42-Framework]
commands:
   circuit_list:
      description: List all types and circuits in the current world.
      usage: /circuit_list [types|<player>|all]
      permission: circuit.list
      permission-message: You don't have permission
permissions:
    circuit.*:
        description: Gives access to all circuit commands
        children:
            circuit.list: true
    circuit.list:
        description: Allows you to list all circuits in the current world
        default: true
